version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    user: "www-data"
    container_name: reception_app_dev
    env_file:
      - ./docker/.env.dev
    environment:
      - PHP_FPM_LISTEN=/var/run/php/php-fpm.sock
      - APP_NAME
      - APP_URL
      - APP_KEY
      - APP_ENV
      - APP_TIMEZONE
      - APP_DEBUG
      - DB_CONNECTION
      - DB_HOST
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - JWT_SECRET
    volumes:
      - ./:/app:rw
    #   - /app/node_modules
    #   - /app/bootstrap/cache
    ports:
      - "8008:8000"
    networks:
      - reception_dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      db:
        condition: service_healthy

  db:
      image: 6c55ddbef969
      container_name: reception_db_dev
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
      volumes:
        - reception_db_dev:/var/lib/mysql
      networks:
        - reception_dev
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}"]
        interval: 5s
        timeout: 5s
        retries: 5

volumes:
  reception_db_dev:
  reception_pgadmin_dev:

networks:
  reception_dev:
    driver: bridge

